import typer
import requests
from typing import Optional
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich import box
from conclave.cli.client import get, RemoteAPIError, _server_url, get_headers, get_request_ssl_config

app = typer.Typer(help="Generate and export compliance and operational reports")
console = Console()

@app.callback()
def callback():
    """
    Report command group callback.
    """
    pass

@app.command(name="generate")
def generate_report(
    report_type: str = typer.Argument(..., help="Report type (audit, training, organization, user_activity, node_inventory, governance_compliance, system_health)"),
    start_date: Optional[str] = typer.Option(None, "--start-date", help="Start date (YYYY-MM-DD)"),
    end_date: Optional[str] = typer.Option(None, "--end-date", help="End date (YYYY-MM-DD)")
):
    """
    Generate and view the summary of a report.
    """
    try:
        query_parts = [f"type={report_type}"]
        if start_date:
            query_parts.append(f"start_date={start_date}")
        if end_date:
            query_parts.append(f"end_date={end_date}")
        query_str = "&".join(query_parts)
        
        report = get(f"/reports/generate?{query_str}")
        
        console.print()
        meta_table = Table(box=None, show_header=False)
        meta_table.add_column("Key", style="bold cyan")
        meta_table.add_column("Val")
        meta_table.add_row("Report ID", report.get("id"))
        meta_table.add_row("Generated By", report.get("generated_by"))
        meta_table.add_row("Organization", report.get("organization"))
        meta_table.add_row("Date Range", report.get("date_range"))
        meta_table.add_row("Timestamp", report.get("timestamp"))
        
        console.print(Panel(
            meta_table,
            title=f"[bold white]{report.get('title')}[/bold white]",
            border_style="bright_blue",
            expand=False
        ))
        
        console.print("\n[bold white]Executive Summary[/bold white]")
        summary_table = Table(box=box.ROUNDED, border_style="bright_blue", header_style="bold bright_blue")
        summary_table.add_column("Metric", style="bold white")
        summary_table.add_column("Value", style="yellow")
        
        summary = report.get("summary", {})
        for k, v in summary.items():
            metric_name = k.replace("_", " ").title()
            if isinstance(v, dict):
                v_str = ", ".join(f"{dk}: {dv}" for dk, dv in v.items())
            else:
                v_str = str(v)
            summary_table.add_row(metric_name, v_str)
            
        console.print(summary_table)
        
        detail_len = len(report.get("detailed_data", []))
        console.print(f"\n[dim]Contains {detail_len} detailed data record(s). Run 'conclave report export' to export full logs.[/dim]\n")
        
    except RemoteAPIError as e:
        console.print(f"[bold red]Error:[/bold red] {e}")

@app.command(name="export")
def export_report(
    report_type: str = typer.Argument(..., help="Report type"),
    format: str = typer.Argument(..., help="Export format (pdf, csv, json)"),
    output_path: str = typer.Argument(..., help="Local filepath to save output"),
    start_date: Optional[str] = typer.Option(None, "--start-date", help="Start date (YYYY-MM-DD)"),
    end_date: Optional[str] = typer.Option(None, "--end-date", help="End date (YYYY-MM-DD)")
):
    """
    Generate and export a report to a local file (PDF, CSV, JSON).
    """
    try:
        query_parts = [f"type={report_type}", f"format={format}"]
        if start_date:
            query_parts.append(f"start_date={start_date}")
        if end_date:
            query_parts.append(f"end_date={end_date}")
        query_str = "&".join(query_parts)
        
        url = f"{_server_url()}/reports/export?{query_str}"
        r = requests.get(url, headers=get_headers(), **get_request_ssl_config())
        
        if r.status_code == 401:
            raise RemoteAPIError("Authentication required. Please log in using 'auth login'.")
        if r.status_code == 403:
            detail = r.json().get("detail", "Forbidden: you do not have permission.")
            raise RemoteAPIError(detail)
        if r.status_code == 200:
            with open(output_path, "wb") as f:
                f.write(r.content)
            console.print()
            console.print(f"[bold green]Success:[/bold green] Report exported to '{output_path}'.")
            console.print()
            return
            
        try:
            detail = r.json().get("detail", "Unknown server error")
        except Exception:
            detail = f"Server returned error code {r.status_code}"
        raise RemoteAPIError(detail)
        
    except RemoteAPIError as e:
        console.print(f"[bold red]Error:[/bold red] {e}")
    except Exception as e:
        console.print(f"[bold red]Error writing file:[/bold red] {e}")


@app.command(name="hipaa")
def hipaa_compliance():
    """
    Run HIPAA security safeguard checks and display the readiness scorecard.
    """
    try:
        report = get("/reports/compliance/hipaa")
        
        console.print()
        console.print(f"[bold cyan]*** Conclave HIPAA Security Safeguard Audit Scorecard ***[/bold cyan]")
        console.print(f"[dim]Timestamp: {report.get('timestamp')}[/dim]\n")
        
        score = report.get("readiness_score", 0)
        score_color = "green" if score >= 80 else "yellow" if score >= 50 else "red"
        console.print(Panel(
            f"Overall HIPAA Compliance Readiness: [bold {score_color}]{score}%[/bold {score_color}]",
            border_style=score_color,
            expand=False,
            padding=(1, 3)
        ))
        console.print()
        
        table = Table(
            title="[bold white]HIPAA Audit Controls Checklist[/bold white]",
            title_justify="left",
            box=box.ROUNDED,
            border_style="bright_blue",
            header_style="bold bright_blue",
            padding=(0, 2)
        )
        table.add_column("Safeguard Ref", style="cyan", width=16)
        table.add_column("Check Safeguard Name", style="bold white")
        table.add_column("Status", style="bold")
        
        for check in report.get("checks", []):
            status_str = "[bold green]PASS[/bold green]" if check["passed"] else "[bold red]FAIL[/bold red]"
            table.add_row(
                check["safeguard"],
                check["name"],
                status_str
            )
        console.print(table)
        console.print()
        
        # Display details/fail warnings
        console.print("[bold white]Detailed Findings & Audit Trails:[/bold white]")
        for check in report.get("checks", []):
            icon = "[green][OK][/green]" if check["passed"] else "[red][X][/red]"
            console.print(f"\n{icon} [bold cyan]{check['name']}[/bold cyan] ({check['safeguard']})")
            for detail in check.get("details", []):
                console.print(f"  - {detail}")
        console.print()
        
    except RemoteAPIError as e:
        console.print(f"[bold red]Error:[/bold red] {e}")


@app.command(name="gdpr")
def gdpr_compliance():
    """
    Run GDPR data protection audit checks and display the readiness scorecard.
    """
    try:
        report = get("/reports/compliance/gdpr")
        
        console.print()
        console.print(f"[bold cyan]*** Conclave GDPR Data Protection Safeguard Audit Scorecard ***[/bold cyan]")
        console.print(f"[dim]Timestamp: {report.get('timestamp')}[/dim]\n")
        
        score = report.get("readiness_score", 0)
        score_color = "green" if score >= 80 else "yellow" if score >= 50 else "red"
        console.print(Panel(
            f"Overall GDPR Compliance Readiness: [bold {score_color}]{score}%[/bold {score_color}]",
            border_style=score_color,
            expand=False,
            padding=(1, 3)
        ))
        console.print()
        
        table = Table(
            title="[bold white]GDPR Safeguards Checklist[/bold white]",
            title_justify="left",
            box=box.ROUNDED,
            border_style="bright_blue",
            header_style="bold bright_blue",
            padding=(0, 2)
        )
        table.add_column("Article Ref", style="cyan", width=16)
        table.add_column("Check Safeguard Name", style="bold white")
        table.add_column("Status", style="bold")
        
        for check in report.get("checks", []):
            status_str = "[bold green]PASS[/bold green]" if check["passed"] else "[bold red]FAIL[/bold red]"
            table.add_row(
                check["safeguard"],
                check["name"],
                status_str
            )
        console.print(table)
        console.print()
        
        # Display details/fail warnings
        console.print("[bold white]Detailed Findings & Audit Trails:[/bold white]")
        for check in report.get("checks", []):
            icon = "[green][OK][/green]" if check["passed"] else "[red][X][/red]"
            console.print(f"\n{icon} [bold cyan]{check['name']}[/bold cyan] ({check['safeguard']})")
            for detail in check.get("details", []):
                console.print(f"  - {detail}")
        console.print()
        
    except RemoteAPIError as e:
        console.print(f"[bold red]Error:[/bold red] {e}")
